authors:
  cyberexplorer:
    name: Cyberexplorer
    description: AstraEditor 的维护者
    avatar: assets/cyberexplorer.jpg
    url: https://cyberneko.cn
  koshino:
    name: _KOSHINO_
    description: AstraEditor 的创建者
    avatar: assets/koshino.jpeg
    url: https://space.bilibili.com/520948922
  xiaoxiaoshine:
    name: 晓晓Shine
    description: AstraEditor 的维护者
    avatar: assets/xiaoxiaoshine.jpeg
    url: https://space.bilibili.com/3546791056247283